<template>
  <div>
    <el-button @click="drawer = true" :size="size" icon="fa fa-plus-square-o"></el-button>
    <el-drawer :visible.sync="drawer" size="500px" :with-header="false">
      <el-collapse v-model="activeNames" @change="handleChange">
        <el-collapse-item
          v-for="(icon, index) in icon_data"
          :key="index"
          :title="icon.lable_name"
          :name="index"
          style="margin:10px"
        >
          <el-row :gutter="10" style="padding:10px">
            <el-col v-for="(name, i) in icon.label_data" :key="i" span="1">
              <i :class="'fa fa-' + name.icon_name" @click="choose_icon(index,i)" id="icon"></i>
            </el-col>
          </el-row>
        </el-collapse-item>
      </el-collapse>
    </el-drawer>
  </div>
</template>
<script>
export default {
    props:["size"],
  data() {
    return {
      drawer: false,
      activeNames: ["0"],
      icon: "",
      icon_data: [
        {
          lable_name: "新增图标",
          label_data: [
            { icon_name: "address-book" },
            { icon_name: "address-book-o" },
            { icon_name: "address-card" },
            { icon_name: "address-card-o" },
            { icon_name: "bandcamp" },
            { icon_name: "bath" },
            { icon_name: "bathtub" },
            { icon_name: "drivers-license" },
            { icon_name: "drivers-license-o" },
            { icon_name: "eercast" },
            { icon_name: "envelope-open" },
            { icon_name: "envelope-open-o" },
            { icon_name: "etsy" },
            { icon_name: "free-code-camp" },
            { icon_name: "grav" },
            { icon_name: "handshake-o" },
            { icon_name: "id-badge" },
            { icon_name: "id-card" },
            { icon_name: "id-card-o" },
            { icon_name: "imdb" },
            { icon_name: "linode" },
            { icon_name: "meetup" },
            { icon_name: "microchip" },
            { icon_name: "podcast" },
            { icon_name: "quora" },
            { icon_name: "ravelry" },
            { icon_name: "s15" },
            { icon_name: "shower" },
            { icon_name: "snowflake-o" },
            { icon_name: "superpowers" },
            { icon_name: "telegram" },
            { icon_name: "thermometer" },
            { icon_name: "thermometer-0" },
            { icon_name: "thermometer-1" },
            { icon_name: "thermometer-2" },
            { icon_name: "thermometer-3" },
            { icon_name: "thermometer-4" },
            { icon_name: "thermometer-empty" },
            { icon_name: "thermometer-full" },
            { icon_name: "thermometer-half" },
            { icon_name: "thermometer-quarter" },
            { icon_name: "thermometer-three-quarters" },
            { icon_name: "times-rectangle" },
            { icon_name: "times-rectangle-o" },
            { icon_name: "user-circle" },
            { icon_name: "user-circle-o" },
            { icon_name: "user-o" },
            { icon_name: "vcard" },
            { icon_name: "vcard-o" },
            { icon_name: "window-close" },
            { icon_name: "window-close-o" },
            { icon_name: "window-maximize" },
            { icon_name: "window-minimize" },
            { icon_name: "window-restore" },
            { icon_name: "wpexplorer" },
          ],
        },
        {
          lable_name: "网页常用",
          label_data: [
            { icon_name: "address-book" },
            { icon_name: "address-book-o" },
            { icon_name: "address-card" },
            { icon_name: "address-card-o" },
            { icon_name: "adjust" },
            { icon_name: "american-sign-language-interpreting" },
            { icon_name: "anchor" },
            { icon_name: "archive" },
            { icon_name: "area-chart" },
            { icon_name: "arrows" },
            { icon_name: "arrows-h" },
            { icon_name: "arrows-v" },
            { icon_name: "asl-interpreting" },
            { icon_name: "assistive-listening-systems" },
            { icon_name: "asterisk" },
            { icon_name: "at" },
            { icon_name: "audio-description" },
            { icon_name: "automobile" },
            { icon_name: "balance-scale" },
            { icon_name: "ban" },
            { icon_name: "bank" },
            { icon_name: "bar-chart" },
            { icon_name: "bar-chart-o" },
            { icon_name: "barcode" },
            { icon_name: "bars" },
            { icon_name: "bath" },
            { icon_name: "bathtub" },
            { icon_name: "battery" },
            { icon_name: "battery-0" },
            { icon_name: "battery-1" },
            { icon_name: "battery-2" },
            { icon_name: "battery-3" },
            { icon_name: "battery-4" },
            { icon_name: "battery-empty" },
            { icon_name: "battery-full" },
            { icon_name: "battery-half" },
            { icon_name: "battery-quarter" },
            { icon_name: "battery-three-quarters" },
            { icon_name: "bed" },
            { icon_name: "beer" },
            { icon_name: "bell" },
            { icon_name: "bell-o" },
            { icon_name: "bell-slash" },
            { icon_name: "bell-slash-o" },
            { icon_name: "bicycle" },
            { icon_name: "binoculars" },
            { icon_name: "birthday-cake" },
            { icon_name: "blind" },
            { icon_name: "bluetooth" },
            { icon_name: "bluetooth-b" },
            { icon_name: "bolt" },
            { icon_name: "bomb" },
            { icon_name: "book" },
            { icon_name: "bookmark" },
            { icon_name: "bookmark-o" },
            { icon_name: "braille" },
            { icon_name: "briefcase" },
            { icon_name: "bug" },
            { icon_name: "building" },
            { icon_name: "building-o" },
            { icon_name: "bullhorn" },
            { icon_name: "bullseye" },
            { icon_name: "bus" },
            { icon_name: "cab" },
            { icon_name: "calculator" },
            { icon_name: "calendar" },
            { icon_name: "calendar-check-o" },
            { icon_name: "calendar-minus-o" },
            { icon_name: "calendar-o" },
            { icon_name: "calendar-plus-o" },
            { icon_name: "calendar-times-o" },
            { icon_name: "camera" },
            { icon_name: "camera-retro" },
            { icon_name: "car" },
            { icon_name: "caret-square-o-down" },
            { icon_name: "caret-square-o-left" },
            { icon_name: "caret-square-o-right" },
            { icon_name: "caret-square-o-up" },
            { icon_name: "cart-arrow-down" },
            { icon_name: "cart-plus" },
            { icon_name: "cc" },
            { icon_name: "certificate" },
            { icon_name: "check" },
            { icon_name: "check-circle" },
            { icon_name: "check-circle-o" },
            { icon_name: "check-square" },
            { icon_name: "check-square-o" },
            { icon_name: "child" },
            { icon_name: "circle" },
            { icon_name: "circle-o" },
            { icon_name: "circle-o-notch" },
            { icon_name: "circle-thin" },
            { icon_name: "clock-o" },
            { icon_name: "clone" },
            { icon_name: "close" },
            { icon_name: "cloud" },
            { icon_name: "cloud-download" },
            { icon_name: "cloud-upload" },
            { icon_name: "code" },
            { icon_name: "code-fork" },
            { icon_name: "coffee" },
            { icon_name: "cog" },
            { icon_name: "cogs" },
            { icon_name: "comment" },
            { icon_name: "comment-o" },
            { icon_name: "commenting" },
            { icon_name: "commenting-o" },
            { icon_name: "comments" },
            { icon_name: "comments-o" },
            { icon_name: "compass" },
            { icon_name: "copyright" },
            { icon_name: "creative-commons" },
            { icon_name: "credit-card" },
            { icon_name: "credit-card-alt" },
            { icon_name: "crop" },
            { icon_name: "crosshairs" },
            { icon_name: "cube" },
            { icon_name: "cubes" },
            { icon_name: "cutlery" },
            { icon_name: "dashboard" },
            { icon_name: "database" },
            { icon_name: "deaf" },
            { icon_name: "deafness" },
            { icon_name: "desktop" },
            { icon_name: "diamond" },
            { icon_name: "dot-circle-o" },
            { icon_name: "download" },
            { icon_name: "drivers-license" },
            { icon_name: "drivers-license-o" },
            { icon_name: "edit" },
            { icon_name: "ellipsis-h" },
            { icon_name: "ellipsis-v" },
            { icon_name: "envelope" },
            { icon_name: "envelope-o" },
            { icon_name: "envelope-open" },
            { icon_name: "envelope-open-o" },
            { icon_name: "envelope-square" },
            { icon_name: "eraser" },
            { icon_name: "exchange" },
            { icon_name: "exclamation" },
            { icon_name: "exclamation-circle" },
            { icon_name: "exclamation-triangle" },
            { icon_name: "external-link" },
            { icon_name: "external-link-square" },
            { icon_name: "eye" },
            { icon_name: "eye-slash" },
            { icon_name: "eyedropper" },
            { icon_name: "fax" },
            { icon_name: "feed" },
            { icon_name: "female" },
            { icon_name: "fighter-jet" },
            { icon_name: "file-archive-o" },
            { icon_name: "file-audio-o" },
            { icon_name: "file-code-o" },
            { icon_name: "file-excel-o" },
            { icon_name: "file-image-o" },
            { icon_name: "file-movie-o" },
            { icon_name: "file-pdf-o" },
            { icon_name: "file-photo-o" },
            { icon_name: "file-picture-o" },
            { icon_name: "file-powerpoint-o" },
            { icon_name: "file-sound-o" },
            { icon_name: "file-video-o" },
            { icon_name: "file-word-o" },
            { icon_name: "file-zip-o" },
            { icon_name: "film" },
            { icon_name: "filter" },
            { icon_name: "fire" },
            { icon_name: "fire-extinguisher" },
            { icon_name: "flag" },
            { icon_name: "flag-checkered" },
            { icon_name: "flag-o" },
            { icon_name: "flash" },
            { icon_name: "flask" },
            { icon_name: "folder" },
            { icon_name: "folder-o" },
            { icon_name: "folder-open" },
            { icon_name: "folder-open-o" },
            { icon_name: "frown-o" },
            { icon_name: "futbol-o" },
            { icon_name: "gamepad" },
            { icon_name: "gavel" },
            { icon_name: "gear" },
            { icon_name: "gears" },
            { icon_name: "gift" },
            { icon_name: "glass" },
            { icon_name: "globe" },
            { icon_name: "graduation-cap" },
            { icon_name: "group" },
            { icon_name: "hand-grab-o" },
            { icon_name: "hand-lizard-o" },
            { icon_name: "hand-paper-o" },
            { icon_name: "hand-peace-o" },
            { icon_name: "hand-pointer-o" },
            { icon_name: "hand-rock-o" },
            { icon_name: "hand-scissors-o" },
            { icon_name: "hand-spock-o" },
            { icon_name: "hand-stop-o" },
            { icon_name: "handshake-o" },
            { icon_name: "hard-of-hearing" },
            { icon_name: "hashtag" },
            { icon_name: "hdd-o" },
            { icon_name: "headphones" },
            { icon_name: "heart" },
            { icon_name: "heart-o" },
            { icon_name: "heartbeat" },
            { icon_name: "history" },
            { icon_name: "home" },
            { icon_name: "hotel" },
            { icon_name: "hourglass" },
            { icon_name: "hourglass-1" },
            { icon_name: "hourglass-2" },
            { icon_name: "hourglass-3" },
            { icon_name: "hourglass-end" },
            { icon_name: "hourglass-half" },
            { icon_name: "hourglass-o" },
            { icon_name: "hourglass-start" },
            { icon_name: "i-cursor" },
            { icon_name: "id-badge" },
            { icon_name: "id-card" },
            { icon_name: "id-card-o" },
            { icon_name: "image" },
            { icon_name: "inbox" },
            { icon_name: "industry" },
            { icon_name: "info" },
            { icon_name: "info-circle" },
            { icon_name: "institution" },
            { icon_name: "key" },
            { icon_name: "keyboard-o" },
            { icon_name: "language" },
            { icon_name: "laptop" },
            { icon_name: "leaf" },
            { icon_name: "legal" },
            { icon_name: "lemon-o" },
            { icon_name: "level-down" },
            { icon_name: "level-up" },
            { icon_name: "life-bouy" },
            { icon_name: "life-buoy" },
            { icon_name: "life-ring" },
            { icon_name: "life-saver" },
            { icon_name: "lightbulb-o" },
            { icon_name: "line-chart" },
            { icon_name: "location-arrow" },
            { icon_name: "lock" },
            { icon_name: "low-vision" },
            { icon_name: "magic" },
            { icon_name: "magnet" },
            { icon_name: "mail-forward" },
            { icon_name: "mail-reply" },
            { icon_name: "mail-reply-all" },
            { icon_name: "male" },
            { icon_name: "map" },
            { icon_name: "map-marker" },
            { icon_name: "map-o" },
            { icon_name: "map-pin" },
            { icon_name: "map-signs" },
            { icon_name: "meh-o" },
            { icon_name: "microchip" },
            { icon_name: "microphone" },
            { icon_name: "microphone-slash" },
            { icon_name: "minus" },
            { icon_name: "minus-circle" },
            { icon_name: "minus-square" },
            { icon_name: "minus-square-o" },
            { icon_name: "mobile" },
            { icon_name: "mobile-phone" },
            { icon_name: "money" },
            { icon_name: "moon-o" },
            { icon_name: "mortar-board" },
            { icon_name: "motorcycle" },
            { icon_name: "mouse-pointer" },
            { icon_name: "music" },
            { icon_name: "navicon" },
            { icon_name: "newspaper-o" },
            { icon_name: "object-group" },
            { icon_name: "object-ungroup" },
            { icon_name: "paint-brush" },
            { icon_name: "paper-plane" },
            { icon_name: "paper-plane-o" },
            { icon_name: "paw" },
            { icon_name: "pencil" },
            { icon_name: "pencil-square" },
            { icon_name: "pencil-square-o" },
            { icon_name: "percent" },
            { icon_name: "phone" },
            { icon_name: "phone-square" },
            { icon_name: "photo" },
            { icon_name: "picture-o" },
            { icon_name: "pie-chart" },
            { icon_name: "plane" },
            { icon_name: "plug" },
            { icon_name: "plus" },
            { icon_name: "plus-circle" },
            { icon_name: "plus-square" },
            { icon_name: "plus-square-o" },
            { icon_name: "podcast" },
            { icon_name: "power-off" },
            { icon_name: "print" },
            { icon_name: "puzzle-piece" },
            { icon_name: "qrcode" },
            { icon_name: "question" },
            { icon_name: "question-circle" },
            { icon_name: "question-circle-o" },
            { icon_name: "quote-left" },
            { icon_name: "quote-right" },
            { icon_name: "random" },
            { icon_name: "recycle" },
            { icon_name: "refresh" },
            { icon_name: "registered" },
            { icon_name: "remove" },
            { icon_name: "reorder" },
            { icon_name: "reply" },
            { icon_name: "reply-all" },
            { icon_name: "retweet" },
            { icon_name: "road" },
            { icon_name: "rocket" },
            { icon_name: "rss" },
            { icon_name: "rss-square" },
            { icon_name: "s15" },
            { icon_name: "search" },
            { icon_name: "search-minus" },
            { icon_name: "search-plus" },
            { icon_name: "send" },
            { icon_name: "send-o" },
            { icon_name: "server" },
            { icon_name: "share" },
            { icon_name: "share-alt" },
            { icon_name: "share-alt-square" },
            { icon_name: "share-square" },
            { icon_name: "share-square-o" },
            { icon_name: "shield" },
            { icon_name: "ship" },
            { icon_name: "shopping-bag" },
            { icon_name: "shopping-basket" },
            { icon_name: "shopping-cart" },
            { icon_name: "shower" },
            { icon_name: "sign-in" },
            { icon_name: "sign-language" },
            { icon_name: "sign-out" },
            { icon_name: "signal" },
            { icon_name: "signing" },
            { icon_name: "sitemap" },
            { icon_name: "sliders" },
            { icon_name: "smile-o" },
            { icon_name: "snowflake-o" },
            { icon_name: "soccer-ball-o" },
            { icon_name: "sort" },
            { icon_name: "sort-alpha-asc" },
            { icon_name: "sort-alpha-desc" },
            { icon_name: "sort-amount-asc" },
            { icon_name: "sort-amount-desc" },
            { icon_name: "sort-asc" },
            { icon_name: "sort-desc" },
            { icon_name: "sort-down" },
            { icon_name: "sort-numeric-asc" },
            { icon_name: "sort-numeric-desc" },
            { icon_name: "sort-up" },
            { icon_name: "space-shuttle" },
            { icon_name: "spinner" },
            { icon_name: "spoon" },
            { icon_name: "square" },
            { icon_name: "square-o" },
            { icon_name: "star" },
            { icon_name: "star-half" },
            { icon_name: "star-half-empty" },
            { icon_name: "star-half-full" },
            { icon_name: "star-half-o" },
            { icon_name: "star-o" },
            { icon_name: "sticky-note" },
            { icon_name: "sticky-note-o" },
            { icon_name: "street-view" },
            { icon_name: "suitcase" },
            { icon_name: "sun-o" },
            { icon_name: "support" },
            { icon_name: "tablet" },
            { icon_name: "tachometer" },
            { icon_name: "tag" },
            { icon_name: "tags" },
            { icon_name: "tasks" },
            { icon_name: "taxi" },
            { icon_name: "television" },
            { icon_name: "terminal" },
            { icon_name: "thermometer" },
            { icon_name: "thermometer-0" },
            { icon_name: "thermometer-1" },
            { icon_name: "thermometer-2" },
            { icon_name: "thermometer-3" },
            { icon_name: "thermometer-4" },
            { icon_name: "thermometer-empty" },
            { icon_name: "thermometer-full" },
            { icon_name: "thermometer-half" },
            { icon_name: "thermometer-quarter" },
            { icon_name: "thermometer-three-quarters" },
            { icon_name: "thumb-tack" },
            { icon_name: "thumbs-down" },
            { icon_name: "thumbs-o-down" },
            { icon_name: "thumbs-o-up" },
            { icon_name: "thumbs-up" },
            { icon_name: "ticket" },
            { icon_name: "times" },
            { icon_name: "times-circle" },
            { icon_name: "times-circle-o" },
            { icon_name: "times-rectangle" },
            { icon_name: "times-rectangle-o" },
            { icon_name: "tint" },
            { icon_name: "toggle-down" },
            { icon_name: "toggle-left" },
            { icon_name: "toggle-off" },
            { icon_name: "toggle-on" },
            { icon_name: "toggle-right" },
            { icon_name: "toggle-up" },
            { icon_name: "trademark" },
            { icon_name: "trash" },
            { icon_name: "trash-o" },
            { icon_name: "tree" },
            { icon_name: "trophy" },
            { icon_name: "truck" },
            { icon_name: "tty" },
            { icon_name: "tv" },
            { icon_name: "umbrella" },
            { icon_name: "universal-access" },
            { icon_name: "university" },
            { icon_name: "unlock" },
            { icon_name: "unlock-alt" },
            { icon_name: "unsorted" },
            { icon_name: "upload" },
            { icon_name: "user" },
            { icon_name: "user-circle" },
            { icon_name: "user-circle-o" },
            { icon_name: "user-o" },
            { icon_name: "user-plus" },
            { icon_name: "user-secret" },
            { icon_name: "user-times" },
            { icon_name: "users" },
            { icon_name: "vcard" },
            { icon_name: "vcard-o" },
            { icon_name: "video-camera" },
            { icon_name: "volume-control-phone" },
            { icon_name: "volume-down" },
            { icon_name: "volume-off" },
            { icon_name: "volume-up" },
            { icon_name: "warning" },
            { icon_name: "wheelchair" },
            { icon_name: "wheelchair-alt" },
            { icon_name: "wifi" },
            { icon_name: "window-close" },
            { icon_name: "window-close-o" },
            { icon_name: "window-maximize" },
            { icon_name: "window-minimize" },
            { icon_name: "window-restore" },
            { icon_name: "wrench" },
            { icon_name: "" },
          ],
        },
        {
          lable_name: "常用手势",
          label_data: [
            { icon_name: "hand-grab-o" },
            { icon_name: "hand-lizard-o" },
            { icon_name: "hand-o-down" },
            { icon_name: "hand-o-left" },
            { icon_name: "hand-o-right" },
            { icon_name: "hand-o-up" },
            { icon_name: "hand-paper-o" },
            { icon_name: "hand-peace-o" },
            { icon_name: "hand-pointer-o" },
            { icon_name: "hand-rock-o" },
            { icon_name: "hand-scissors-o" },
            { icon_name: "hand-spock-o" },
            { icon_name: "hand-stop-o" },
            { icon_name: "thumbs-down" },
            { icon_name: "thumbs-o-down" },
            { icon_name: "thumbs-o-up" },
            { icon_name: "thumbs-up" },
          ],
        },
        {
          lable_name: "辅助功能",
          label_data: [
            { icon_name: "american-sign-language-interpreting" },
            { icon_name: "asl-interpreting" },
            { icon_name: "assistive-listening-systems" },
            { icon_name: "audio-description" },
            { icon_name: "blind" },
            { icon_name: "braille" },
            { icon_name: "cc" },
            { icon_name: "deaf" },
            { icon_name: "deafness" },
            { icon_name: "hard-of-hearing" },
            { icon_name: "low-vision" },
            { icon_name: "question-circle-o" },
            { icon_name: "sign-language" },
            { icon_name: "signing" },
            { icon_name: "tty" },
            { icon_name: "universal-access" },
            { icon_name: "volume-control-phone" },
            { icon_name: "wheelchair" },
            { icon_name: "wheelchair-alt" },
          ],
        },
        {
          lable_name: "运输",
          label_data: [
            { icon_name: "ambulance" },
            { icon_name: "automobile" },
            { icon_name: "bicycle" },
            { icon_name: "bus" },
            { icon_name: "cab" },
            { icon_name: "car" },
            { icon_name: "fighter-jet" },
            { icon_name: "motorcycle" },
            { icon_name: "plane" },
            { icon_name: "rocket" },
            { icon_name: "ship" },
            { icon_name: "space-shuttle" },
            { icon_name: "subway" },
            { icon_name: "taxi" },
            { icon_name: "train" },
            { icon_name: "truck" },
            { icon_name: "wheelchair" },
            { icon_name: "wheelchair-alt" },
          ],
        },
        {
          lable_name: "性别",
          label_data: [
            { icon_name: "genderless" },
            { icon_name: "intersex" },
            { icon_name: "mars" },
            { icon_name: "mars-double" },
            { icon_name: "mars-stroke" },
            { icon_name: "mars-stroke-h" },
            { icon_name: "mars-stroke-v" },
            { icon_name: "mercury" },
            { icon_name: "neuter" },
            { icon_name: "transgender" },
            { icon_name: "transgender-alt" },
            { icon_name: "venus" },
            { icon_name: "venus-double" },
            { icon_name: "venus-mars" },
          ],
        },
        {
          lable_name: "文件类型",
          label_data: [
            { icon_name: "file" },
            { icon_name: "file-archive-o" },
            { icon_name: "file-audio-o" },
            { icon_name: "file-code-o" },
            { icon_name: "file-excel-o" },
            { icon_name: "file-image-o" },
            { icon_name: "file-movie-o" },
            { icon_name: "file-o" },
            { icon_name: "file-pdf-o" },
            { icon_name: "file-photo-o" },
            { icon_name: "file-picture-o" },
            { icon_name: "file-powerpoint-o" },
            { icon_name: "file-sound-o" },
            { icon_name: "file-text" },
            { icon_name: "file-text-o" },
            { icon_name: "file-video-o" },
            { icon_name: "file-word-o" },
            { icon_name: "file-zip-o" },
          ],
        },
        {
          lable_name: "可旋转",
          label_data: [
            { icon_name: "circle-o-notch" },
            { icon_name: "cog" },
            { icon_name: "gear" },
            { icon_name: "refresh" },
            { icon_name: "spinner" },
          ],
        },
        {
          lable_name: "表单",
          label_data: [
            { icon_name: "check-square" },
            { icon_name: "check-square-o" },
            { icon_name: "circle" },
            { icon_name: "circle-o" },
            { icon_name: "dot-circle-o" },
            { icon_name: "minus-square" },
            { icon_name: "minus-square-o" },
            { icon_name: "plus-square" },
            { icon_name: "plus-square-o" },
            { icon_name: "square" },
            { icon_name: "square-o" },
          ],
        },
        {
          lable_name: "支付",
          label_data: [
            { icon_name: "cc-amex" },
            { icon_name: "cc-diners-club" },
            { icon_name: "cc-discover" },
            { icon_name: "cc-jcb" },
            { icon_name: "cc-mastercard" },
            { icon_name: "cc-paypal" },
            { icon_name: "cc-stripe" },
            { icon_name: "cc-visa" },
            { icon_name: "credit-card" },
            { icon_name: "credit-card-alt" },
            { icon_name: "google-wallet" },
            { icon_name: "paypal" },
          ],
        },
        {
          lable_name: "图表",
          label_data: [
            { icon_name: "area-chart" },
            { icon_name: "bar-chart" },
            { icon_name: "bar-chart-o" },
            { icon_name: "line-chart" },
            { icon_name: "pie-chart" },
          ],
        },
        {
          lable_name: "货币",
          label_data: [
            { icon_name: "bitcoin" },
            { icon_name: "btc" },
            { icon_name: "cny" },
            { icon_name: "dollar" },
            { icon_name: "eur" },
            { icon_name: "euro" },
            { icon_name: "gbp" },
            { icon_name: "gg" },
            { icon_name: "gg-circle" },
            { icon_name: "ils" },
            { icon_name: "inr" },
            { icon_name: "jpy" },
            { icon_name: "krw" },
            { icon_name: "money" },
            { icon_name: "rmb" },
            { icon_name: "rouble" },
            { icon_name: "rub" },
            { icon_name: "ruble" },
            { icon_name: "rupee" },
            { icon_name: "shekel" },
            { icon_name: "sheqel" },
            { icon_name: "try" },
            { icon_name: "turkish-lira" },
            { icon_name: "usd" },
            { icon_name: "won" },
            { icon_name: "yen" },
          ],
        },
        {
          lable_name: "编辑",
          label_data: [
            { icon_name: "align-center" },
            { icon_name: "align-justify" },
            { icon_name: "align-left" },
            { icon_name: "align-right" },
            { icon_name: "bold" },
            { icon_name: "chain" },
            { icon_name: "chain-broken" },
            { icon_name: "clipboard" },
            { icon_name: "columns" },
            { icon_name: "copy" },
            { icon_name: "cut" },
            { icon_name: "dedent" },
            { icon_name: "eraser" },
            { icon_name: "file" },
            { icon_name: "file-o" },
            { icon_name: "file-text" },
            { icon_name: "file-text-o" },
            { icon_name: "files-o" },
            { icon_name: "floppy-o" },
            { icon_name: "font" },
            { icon_name: "header" },
            { icon_name: "indent" },
            { icon_name: "italic" },
            { icon_name: "link" },
            { icon_name: "list" },
            { icon_name: "list-alt" },
            { icon_name: "list-ol" },
            { icon_name: "list-ul" },
            { icon_name: "outdent" },
            { icon_name: "paperclip" },
            { icon_name: "paragraph" },
            { icon_name: "paste" },
            { icon_name: "repeat" },
            { icon_name: "rotate-left" },
            { icon_name: "rotate-right" },
            { icon_name: "save" },
            { icon_name: "scissors" },
            { icon_name: "strikethrough" },
            { icon_name: "subscript" },
            { icon_name: "superscript" },
            { icon_name: "table" },
            { icon_name: "text-height" },
            { icon_name: "text-width" },
            { icon_name: "th" },
            { icon_name: "th-large" },
            { icon_name: "th-list" },
            { icon_name: "underline" },
            { icon_name: "undo" },
            { icon_name: "unlink" },
          ],
        },
        {
          lable_name: "方向",
          label_data: [
            { icon_name: "angle-double-down" },
            { icon_name: "angle-double-left" },
            { icon_name: "angle-double-right" },
            { icon_name: "angle-double-up" },
            { icon_name: "angle-down" },
            { icon_name: "angle-left" },
            { icon_name: "angle-right" },
            { icon_name: "angle-up" },
            { icon_name: "arrow-circle-down" },
            { icon_name: "arrow-circle-left" },
            { icon_name: "arrow-circle-o-down" },
            { icon_name: "arrow-circle-o-left" },
            { icon_name: "arrow-circle-o-right" },
            { icon_name: "arrow-circle-o-up" },
            { icon_name: "arrow-circle-right" },
            { icon_name: "arrow-circle-up" },
            { icon_name: "arrow-down" },
            { icon_name: "arrow-left" },
            { icon_name: "arrow-right" },
            { icon_name: "arrow-up" },
            { icon_name: "arrows" },
            { icon_name: "arrows-alt" },
            { icon_name: "arrows-h" },
            { icon_name: "arrows-v" },
            { icon_name: "caret-down" },
            { icon_name: "caret-left" },
            { icon_name: "caret-right" },
            { icon_name: "caret-square-o-down" },
            { icon_name: "caret-square-o-left" },
            { icon_name: "caret-square-o-right" },
            { icon_name: "caret-square-o-up" },
            { icon_name: "caret-up" },
            { icon_name: "chevron-circle-down" },
            { icon_name: "chevron-circle-left" },
            { icon_name: "chevron-circle-right" },
            { icon_name: "chevron-circle-up" },
            { icon_name: "chevron-down" },
            { icon_name: "chevron-left" },
            { icon_name: "chevron-right" },
            { icon_name: "chevron-up" },
            { icon_name: "exchange" },
            { icon_name: "hand-o-down" },
            { icon_name: "hand-o-left" },
            { icon_name: "hand-o-right" },
            { icon_name: "hand-o-up" },
            { icon_name: "long-arrow-down" },
            { icon_name: "long-arrow-left" },
            { icon_name: "long-arrow-right" },
            { icon_name: "long-arrow-up" },
            { icon_name: "toggle-down" },
            { icon_name: "toggle-left" },
            { icon_name: "toggle-right" },
            { icon_name: "toggle-up" },
          ],
        },
        {
          lable_name: "视频播放",
          label_data: [
            { icon_name: "arrows-alt" },
            { icon_name: "backward" },
            { icon_name: "compress" },
            { icon_name: "eject" },
            { icon_name: "expand" },
            { icon_name: "fast-backward" },
            { icon_name: "fast-forward" },
            { icon_name: "forward" },
            { icon_name: "pause" },
            { icon_name: "pause-circle" },
            { icon_name: "pause-circle-o" },
            { icon_name: "play" },
            { icon_name: "play-circle" },
            { icon_name: "play-circle-o" },
            { icon_name: "random" },
            { icon_name: "step-backward" },
            { icon_name: "step-forward" },
            { icon_name: "stop" },
            { icon_name: "stop-circle" },
            { icon_name: "stop-circle-o" },
            { icon_name: "youtube-play" },
          ],
        },
        {
          lable_name: "标志",
          label_data: [
            { icon_name: "Example of500px" },
            { icon_name: "adn" },
            { icon_name: "amazon" },
            { icon_name: "android" },
            { icon_name: "angellist" },
            { icon_name: "apple" },
            { icon_name: "bandcamp" },
            { icon_name: "behance" },
            { icon_name: "behance-square" },
            { icon_name: "bitbucket" },
            { icon_name: "bitbucket-square" },
            { icon_name: "bitcoin" },
            { icon_name: "black-tie" },
            { icon_name: "bluetooth" },
            { icon_name: "bluetooth-b" },
            { icon_name: "btc" },
            { icon_name: "buysellads" },
            { icon_name: "cc-amex" },
            { icon_name: "cc-diners-club" },
            { icon_name: "cc-discover" },
            { icon_name: "cc-jcb" },
            { icon_name: "cc-mastercard" },
            { icon_name: "cc-paypal" },
            { icon_name: "cc-stripe" },
            { icon_name: "cc-visa" },
            { icon_name: "chrome" },
            { icon_name: "codepen" },
            { icon_name: "codiepie" },
            { icon_name: "connectdevelop" },
            { icon_name: "contao" },
            { icon_name: "css3" },
            { icon_name: "dashcube" },
            { icon_name: "delicious" },
            { icon_name: "deviantart" },
            { icon_name: "digg" },
            { icon_name: "dribbble" },
            { icon_name: "dropbox" },
            { icon_name: "drupal" },
            { icon_name: "edge" },
            { icon_name: "eercast" },
            { icon_name: "empire" },
            { icon_name: "envira" },
            { icon_name: "etsy" },
            { icon_name: "expeditedssl" },
            { icon_name: "fa" },
            { icon_name: "facebook" },
            { icon_name: "facebook-f" },
            { icon_name: "facebook-official" },
            { icon_name: "facebook-square" },
            { icon_name: "firefox" },
            { icon_name: "first-order" },
            { icon_name: "flickr" },
            { icon_name: "font-awesome" },
            { icon_name: "fonticons" },
            { icon_name: "fort-awesome" },
            { icon_name: "forumbee" },
            { icon_name: "foursquare" },
            { icon_name: "free-code-camp" },
            { icon_name: "ge" },
            { icon_name: "get-pocket" },
            { icon_name: "gg" },
            { icon_name: "gg-circle" },
            { icon_name: "git" },
            { icon_name: "git-square" },
            { icon_name: "github" },
            { icon_name: "github-alt" },
            { icon_name: "github-square" },
            { icon_name: "gitlab" },
            { icon_name: "gittip" },
            { icon_name: "glide" },
            { icon_name: "glide-g" },
            { icon_name: "google" },
            { icon_name: "google-plus" },
            { icon_name: "google-plus-circle" },
            { icon_name: "google-plus-official" },
            { icon_name: "google-plus-square" },
            { icon_name: "google-wallet" },
            { icon_name: "gratipay" },
            { icon_name: "grav" },
            { icon_name: "hacker-news" },
            { icon_name: "houzz" },
            { icon_name: "html5" },
            { icon_name: "imdb" },
            { icon_name: "instagram" },
            { icon_name: "internet-explorer" },
            { icon_name: "ioxhost" },
            { icon_name: "joomla" },
            { icon_name: "jsfiddle" },
            { icon_name: "lastfm" },
            { icon_name: "lastfm-square" },
            { icon_name: "leanpub" },
            { icon_name: "linkedin" },
            { icon_name: "linkedin-square" },
            { icon_name: "linode" },
            { icon_name: "linux" },
            { icon_name: "maxcdn" },
            { icon_name: "meanpath" },
            { icon_name: "medium" },
            { icon_name: "meetup" },
            { icon_name: "mixcloud" },
            { icon_name: "modx" },
            { icon_name: "odnoklassniki" },
            { icon_name: "odnoklassniki-square" },
            { icon_name: "opencart" },
            { icon_name: "openid" },
            { icon_name: "opera" },
            { icon_name: "optin-monster" },
            { icon_name: "pagelines" },
            { icon_name: "paypal" },
            { icon_name: "pied-piper" },
            { icon_name: "pied-piper-alt" },
            { icon_name: "pied-piper-pp" },
            { icon_name: "pinterest" },
            { icon_name: "pinterest-p" },
            { icon_name: "pinterest-square" },
            { icon_name: "product-hunt" },
            { icon_name: "qq" },
            { icon_name: "quora" },
            { icon_name: "ra" },
            { icon_name: "ravelry" },
            { icon_name: "rebel" },
            { icon_name: "reddit" },
            { icon_name: "reddit-alien" },
            { icon_name: "reddit-square" },
            { icon_name: "renren" },
            { icon_name: "resistance" },
            { icon_name: "safari" },
            { icon_name: "scribd" },
            { icon_name: "sellsy" },
            { icon_name: "share-alt" },
            { icon_name: "share-alt-square" },
            { icon_name: "shirtsinbulk" },
            { icon_name: "simplybuilt" },
            { icon_name: "skyatlas" },
            { icon_name: "skype" },
            { icon_name: "slack" },
            { icon_name: "slideshare" },
            { icon_name: "snapchat" },
            { icon_name: "snapchat-ghost" },
            { icon_name: "snapchat-square" },
            { icon_name: "soundcloud" },
            { icon_name: "spotify" },
            { icon_name: "stack-exchange" },
            { icon_name: "stack-overflow" },
            { icon_name: "steam" },
            { icon_name: "steam-square" },
            { icon_name: "stumbleupon" },
            { icon_name: "stumbleupon-circle" },
            { icon_name: "superpowers" },
            { icon_name: "telegram" },
            { icon_name: "tencent-weibo" },
            { icon_name: "themeisle" },
            { icon_name: "trello" },
            { icon_name: "tripadvisor" },
            { icon_name: "tumblr" },
            { icon_name: "tumblr-square" },
            { icon_name: "twitch" },
            { icon_name: "twitter" },
            { icon_name: "twitter-square" },
            { icon_name: "usb" },
            { icon_name: "viacoin" },
            { icon_name: "viadeo" },
            { icon_name: "viadeo-square" },
            { icon_name: "vimeo" },
            { icon_name: "vimeo-square" },
            { icon_name: "vine" },
            { icon_name: "vk" },
            { icon_name: "wechat" },
            { icon_name: "weibo" },
            { icon_name: "weixin" },
            { icon_name: "whatsapp" },
            { icon_name: "wikipedia-w" },
            { icon_name: "windows" },
            { icon_name: "wordpress" },
            { icon_name: "wpbeginner" },
            { icon_name: "wpexplorer" },
            { icon_name: "wpforms" },
            { icon_name: "xing" },
            { icon_name: "xing-square" },
            { icon_name: "y-combinator" },
            { icon_name: "y-combinator-square" },
            { icon_name: "yahoo" },
            { icon_name: "yc" },
            { icon_name: "yc-square" },
            { icon_name: "yelp" },
            { icon_name: "yoast" },
            { icon_name: "youtube" },
            { icon_name: "youtube-play" },
            { icon_name: "youtube-square" },
          ],
        },
        {
          lable_name: "医疗",
          label_data: [
            { icon_name: "ambulance" },
            { icon_name: "h-square" },
            { icon_name: "heart" },
            { icon_name: "heart-o" },
            { icon_name: "heartbeat" },
            { icon_name: "hospital-o" },
            { icon_name: "medkit" },
            { icon_name: "plus-square" },
            { icon_name: "stethoscope" },
            { icon_name: "user-md" },
            { icon_name: "wheelchair" },
            { icon_name: "wheelchair-alt" },
          ],
        },
      ],
    };
  },
  methods:{
      choose_icon(index,i){
        //   console.log(this.icon_data[index].label_data[i].icon_name);
          this.$emit('input','fa fa-' +this.icon_data[index].label_data[i].icon_name)
      }
  }
};
</script>
<style scoped>
#icon{
    cursor: pointer;
}
</style>